name: Copy jd files to ql

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 0 */3 * *'

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          repository: kimcrowing/Proxy
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Get list of updated .js and .py files from other repository
        run: |
          mkdir jd_Scripts
          git clone https://github.com/miantj/jd_Scripts.git jd_Scripts
          cd jd_Scripts
          git log --all --since="1 days ago" --format="%H" | while read hash; do 
            git diff --name-only --exclude-dir '*' $hash 
          done > recent_files.txt 
          cat recent_files.txt # 这将显示文件列表以确保它们被找到

      - name: Copy updated files to ql directory in the current repository
        run: |
          while IFS= read -r file; do
            # 只复制根目录下的文件
            if [[ "$file" == *"/"* ]]; then
              echo "$file is not in the root directory, skipping."
            else
              cp "jd_Scripts/$file" ${{ github.workspace }}/test/
              echo "Copied $file to ql directory."
            fi
          done < jd_Scripts/recent_files.txt

      - name: Commit Changes
        run: |
          git config core.ignorecase false
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add test/*
          git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"
          git push          
